// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9B2nlCjcQ9jO38unh5foOIaM04XioQZE',
    appId: '1:532228620739:web:29502eae8549f801a87d76',
    messagingSenderId: '532228620739',
    projectId: 'muslim-soul-app',
    authDomain: 'muslim-soul-app.firebaseapp.com',
    databaseURL: 'https://muslim-soul-app-default-rtdb.firebaseio.com',
    storageBucket: 'muslim-soul-app.appspot.com',
    measurementId: 'G-5B1BYRVE5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPvpsLU6WFxwdB6MAWrpvAOheuFSgQoiM',
    appId: '1:532228620739:android:e8894a29a6ba440ba87d76',
    messagingSenderId: '532228620739',
    projectId: 'muslim-soul-app',
    databaseURL: 'https://muslim-soul-app-default-rtdb.firebaseio.com',
    storageBucket: 'muslim-soul-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB66_ySY5lOswCprMsQW6SE7obCr6LqZjM',
    appId: '1:532228620739:ios:913f3683e1ab5eefa87d76',
    messagingSenderId: '532228620739',
    projectId: 'muslim-soul-app',
    databaseURL: 'https://muslim-soul-app-default-rtdb.firebaseio.com',
    storageBucket: 'muslim-soul-app.appspot.com',
    iosClientId: '532228620739-q9oolb1e2dnqud2ok5jhjnv3gc19f5pr.apps.googleusercontent.com',
    iosBundleId: 'com.example.muslimSoulApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB66_ySY5lOswCprMsQW6SE7obCr6LqZjM',
    appId: '1:532228620739:ios:913f3683e1ab5eefa87d76',
    messagingSenderId: '532228620739',
    projectId: 'muslim-soul-app',
    databaseURL: 'https://muslim-soul-app-default-rtdb.firebaseio.com',
    storageBucket: 'muslim-soul-app.appspot.com',
    iosClientId: '532228620739-q9oolb1e2dnqud2ok5jhjnv3gc19f5pr.apps.googleusercontent.com',
    iosBundleId: 'com.example.muslimSoulApp',
  );
}
